using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CSharpFunctionalExtensions.MinimalApi.Generators;

[Generator]
public class ResultExtensionsGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new ResultSyntaxReceiver());
    }
    
    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not ResultSyntaxReceiver receiver)
            return;
        
        var sourceBuilder = new StringBuilder();
        
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("""
                                 using CSharpFunctionalExtensions;
                                 using IResult = Microsoft.AspNetCore.Http.IResult;
                                 """);
        receiver.RequiredNamespaces
            .Where(@namespace => !@namespace.StartsWith("global"))
            .Distinct()
            .Select(@namespace => $"using {@namespace}")
            .ToList()
            .ForEach(@using => sourceBuilder.AppendLine(@using));
        
        sourceBuilder.AppendLine();
        
        sourceBuilder.AppendLine("public static class ResultExtensions2 {");
        sourceBuilder.AppendLine();
        
        foreach (var mapperClass in receiver.MapperClasses)
        {
            var mapperClassName = mapperClass.Identifier.Text;
            var mappingProperty = mapperClass.Members
                .FirstOrDefault(member => (member as PropertyDeclarationSyntax)?.Identifier.Text == "Mapping") as PropertyDeclarationSyntax;
            var mappingTypes = (mappingProperty?.Type as GenericNameSyntax)?.TypeArgumentList.Arguments
                .Select(type => type.ToString())
                .ToArray();
            
            if (mappingTypes is null || mappingTypes.Length != 2)
                throw new ArgumentException($"Mapping property in class {mapperClassName} must have exactly two generic arguments.");
            
            var resultErrorType = mappingTypes[0];
            var httpResultType = mappingTypes[1];
            
            var method = $$"""
                           public static {{httpResultType}} ToHttpResult<T>(this Result<T,{{resultErrorType}}> result) {
                               if(result.IsFailure)
                                   return new {{mapperClassName}}().Mapping(result.Error);
                                   
                               return TypedResults.Ok(result.Value);
                           }
                           """;
            
            sourceBuilder.AppendLine(method);
        }
        
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("}");
        
        context.AddSource("ResultExtensions2.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }
}