name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Install .NET tools
        run: dotnet tool restore

      - name: Install .NET dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory dist/tests --collect:"XPlat Code Coverage"

      - name: Upload .NET test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: dist/tests/test-results.trx
        if: ${{ always() }}

      - name: Upload .NET test coverage
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-coverage
          path: dist/tests/**/coverage.cobertura.xml
        if: ${{ always() }}

      - name: Lint
        run: dotnet csharpier --check .

      - name: Extract version from tag
        run: |
          # Extract the version from the tag (e.g., 'refs/tags/v1.2.3' -> '1.2.3')
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack -c Release -p:Version=${{ env.VERSION }} --output dist/package

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/package/*.${{ env.VERSION }}.nupkg

      - name: Attach package to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/package/*.${{ env.VERSION }}.nupkg
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true

      - name: Push to NuGet
        run: dotnet nuget push "dist/package/*.${{ env.VERSION }}.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
