name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  test-versions:
    strategy:
      matrix:
        csharpFunctionalExtensionsVersion: [ '2.29.0', '2.*', '3.0.0', '3.*' ]
      fail-fast: false
    uses: ./.github/workflows/test-version.yml
    with:
      csharpFunctionalExtensionsVersion: ${{ matrix.csharpFunctionalExtensionsVersion }}

  publish:
    runs-on: ubuntu-latest
    needs: test-versions
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7
            8
            9.0.201

      - name: Install .NET tools
        run: dotnet tool restore

      - name: Install .NET dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Lint
        run: dotnet csharpier --check .

      - name: Extract version from tag
        run: |
          # Extract the version from the tag (e.g., 'refs/tags/v1.2.3' -> '1.2.3')
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack ./CSharpFunctionalExtensions.HttpResults/CSharpFunctionalExtensions.HttpResults.csproj -c Release -p:Version=${{ env.VERSION }} --output dist/package

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/package/*.${{ env.VERSION }}.nupkg

      - name: Attach package to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/package/*.${{ env.VERSION }}.nupkg
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true

      - name: Push to NuGet
        run: dotnet nuget push "dist/package/*.${{ env.VERSION }}.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
