name: "test-version"

on:
  workflow_call:
    inputs:
      csharpFunctionalExtensionsVersion:
        type: string
        required: true

jobs:
  test-version:
    runs-on: ubuntu-latest
    steps:
      - name: Sanitize version for artifact name
        run: |
          SANITIZED_LIBVERSION=${{ inputs.csharpFunctionalExtensionsVersion }}
          SANITIZED_LIBVERSION=${SANITIZED_LIBVERSION//\*/+}
          echo SANITIZED_LIBVERSION=${SANITIZED_LIBVERSION} >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7
            8
            9.0.201

      - name: Override CSharpFunctionalExtensions Version
        run: |
          dotnet add CSharpFunctionalExtensions.HttpResults.Tests package CSharpFunctionalExtensions --version ${{ inputs.csharpFunctionalExtensionsVersion }}
          dotnet add CSharpFunctionalExtensions.HttpResults.Generators.Tests package CSharpFunctionalExtensions --version ${{ inputs.csharpFunctionalExtensionsVersion }}

      - name: Install .NET dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore -p:ContinuousIntegrationBuild=true

      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity normal --logger "trx;logfilename=test-results.trx" --results-directory dist/tests/${{ env.SANITIZED_LIBVERSION }} --collect:"XPlat Code Coverage" --settings coverlet.runsettings

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Merge coverage files
        run: dotnet-coverage merge dist/tests/${{ env.SANITIZED_LIBVERSION }}/**/coverage.cobertura.xml -f cobertura -o dist/tests/${{ env.SANITIZED_LIBVERSION }}/coverage.xml

      - name: Upload .NET test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results-${{ env.SANITIZED_LIBVERSION }}
          path: dist/tests/${{ env.SANITIZED_LIBVERSION }}/test-results.trx
        if: ${{ always() }}

      - name: Upload .NET test coverage
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-coverage-${{ env.SANITIZED_LIBVERSION }}
          path: dist/tests/${{ env.SANITIZED_LIBVERSION }}/coverage.xml
        if: ${{ always() }}

      - name: Create test result report
        uses: dorny/test-reporter@v2
        with:
          name: Test Results ${{ env.SANITIZED_LIBVERSION }}
          path: dist/tests/${{ env.SANITIZED_LIBVERSION }}/test-results.trx
          badge-title: Test Results ${{ env.SANITIZED_LIBVERSION }}
          reporter: dotnet-trx
        if: ${{ always() }}

      - name: Create test coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: dist/tests/${{ env.SANITIZED_LIBVERSION }}/coverage.xml
          badge: true
          format: markdown
          output: file
        if: ${{ always() }}

      - name: Attach test coverage report to action summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        if: ${{ always() }}
